name: deploy
on: push

jobs:
  deploy_desktop:
    name: desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      # ubuntu: install deps, configure/build
      - name: install deps
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-dev xorg-dev
        if: startsWith(matrix.os, 'ubuntu')
      - name: configure/build (ubuntu)
        run: ./build_desktop_release.bash
        if: startsWith(matrix.os, 'ubuntu')
      # windows: configure/build
      - name: configure/build (win32)
        run: build_desktop_release_win32.cmd
        if: startsWith(matrix.os, 'windows')
        shell: cmd
      - name: configure/build (win64)
        run: build_desktop_release_win64.cmd
        if: startsWith(matrix.os, 'windows')
        shell: cmd
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: _deploy/*

  deploy_web:
    name: web
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: configure/build
        # build_web_release.bash needs to know the emsdk location
        # in order to call: source $EMSDK/emsdk_env.sh:
        env:
          EMSDK: ${{ github.workspace }}/emsdk
        run: ./build_web_release.bash
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: _deploy/*

  deploy_android:
    name: android
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: assemble
        run: ./build_android_release.bash
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: _deploy/*

  deploy_gh_pages:
    name: deploy to gh-pages
    runs-on: ubuntu-20.04
    needs:
      [deploy_web]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: artifact # default name (by not giving any name to actions/upload-artifact@v2)
          path: _artifact
      - name: unzip
        # assuming there is only one *Emscripten.zip file
        run: |
          mkdir _deploy
          unzip _artifact/*Emscripten.zip -d _deploy
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: _deploy
          target-folder: yg_examples
